== schema.adoc
SEE ALSO json-ld.adoc +
https://github.internet2.edu/api-schema

:Email:     hazelton@internet2.edu
:Date:      2020-05-27
:Revision:  00
:SelfLink:  https://github.internet2.edu/api-schema/person
:Editor:    Keith Hazelton
:Email:     hazelton@internet2.edu

[INFO]
====
Revision: {Revision} +
{Date} +
Self-link: {SelfLink} +
Editor: {Editor}, {Email}
====


- - -
_2020-05-26 22:18 Axiom constructs to OWL entities and properties_

link:https://docs.evolveum.com/midpoint/midprivacy/phases/01-data-provenance-prototype/axiom/[Axiom's] five basic data modeling constructs <--> Closest link:https://www.w3.org/TR/owl2-manchester-syntax/[OWL] counterparts 

objects <--> entities +
properties <--> object properties, data properties ? +
containers <--> DAG fragments ? +
object references <--> entity IRIs +
value metadata <--> simple property ? +



- - -
_2020-05-26 10:27 JSON-LD & RDF & OWL_


https://github.com/VirtualFlyBrain/neo4j2owl <= !! A model approach to building information models +
https://github.com/VirtualFlyBrain/VFB_neo4j +
https://github.com/VirtualFlyBrain/VFB_owl <= To be deprecated when VFB 2.0 is released +
https://neo4j.com/graphgist/books-management-graph +
https://www.slideshare.net/thesimonjupp/ontologies-neo4jgraphworkshopberlin +
https://neo4j.com/blog/neo4j-rdf-graph-database-reasoning-engine/ +
https://elixir-europe.org/about-us/how-funded/eu-projects/excelerate <= Another Horizon 2020-funded project +
https://elixir-europe.org/platforms +
https://drive.google.com/file/d/1DNugP5P3qmw1YHqcD9ZS4ogi34vCVtjU/view <= Selected Elixir Core Data Resources +
-  https://www.uniprot.org/ <= protein sequence and functional information +
-  https://string-db.org/cgi/input.pl <= Protein-Protein Interaction Networks, Functional Enrichment Analysis +
-  https://www.ebi.ac.uk/pdbe/ <= collection, org & dissemination of data on biological macromolecular structures +
-  https://www.ebi.ac.uk/intact/ <= free, open source database system and analysis tools for molecular interaction data +
-  https://www.proteinatlas.org/ <= Human protein atlas +
-  https://europepmc.org/ <= Europe PMC +
-  https://europepmc.org/About <= open science platform for access to a worldwide collection of life science pubs +
-  https://www.ebi.ac.uk/chebi/ <= Chemical Entities of Biological Interest +
-  https://www.brenda-enzymes.org/ <= Comprehensive Enzyme Information System +
  
https://www.slideshare.net/thesimonjupp/ontologies-neo4jgraphworkshopberlin +
https://www.w3.org/2013/dwbp/wiki/RDF_AND_JSON-LD_UseCases <= RDF and JSON-LD use cases

* Start w Neo4J for information model drafting
** Could this be the native Axiom representation?
* Migrate up to OWL (using neo4j2owl)
* Save to RDF(a) (trivial re-representation, "save as")
* Re-express RDF as JSON-LD (From RDF to JSON-LD, https://w3c.github.io/json-ld-api/tests/fromRdf-manifest.html)

https://www.researchgate.net/publication/266388960_Semantic_Web_and_Big_Data_meets_Applied_Ontology_The_Ontology_Summit_2014 +
https://www.w3.org/TR/vocab-dcat-2/ <= Data Catalog Vocabulary v2 +
https://niem.github.io/reference/domain-modeling-guide/content/ +
https://www.niem.gov/tools-catalog

- - -
_2020-05-25 21:49 IM and DM_

https://tools.ietf.org/html/rfc3444 <= On the difference between Information Models and Data Models
http://docs.geppetto.org/en/latest/devdocs.html <= open neuro-sci info modeling

- - -
_2020-05-26 08:05 Schema.org as reference point_

https://schema.org/version/8.0/schema-all.html

- - -
_2020-05-13 18:08 Road to Axiom_

https://evolveum.com/data-provenance-milestone-1/ <= Evolveum blog post by Radovan Semancik +
https://evolveum.com/a-road-to-axiom/ <= Evolveum blog post by Radovan Semancik

- - -
_2020-05-04 16:05 Thoughts on Axiom_

Why the ongoing dissatisfaction with existing schema languages?

. lack of common schema metadata
. clunky extensibility
. lack of human-friendly syntax
. lack of libraries for programmatic handling

Look at Evolveum complaints

https://j.mp/evosow <= Item 1, April 28, 2020: Evolveum on schema

Suggestion: JSON-LD's @context gives a perfect way to avoid collisions in extensions

https://www.w3.org/TR/json-ld11/

- - -
_2020-04-29 12:37 alignment of COmanage and Minimal Registry Person_

corePersonJsonSchema.json <= started with JSON Schema for Minimal Registry Person

- - -
_2020-04-23 15:17 DW (Incl FM) Schema_

see icpData.adoc

- - -
_2020-04-21 09:33 Evolveum Axiom Schema Language proposal_

https://docs.evolveum.com/midpoint/midprivacy/phases/01-data-provenance-prototype/axiom/ +
https://wiki.evolveum.com/display/midPoint/Prism+Schema <= related

- - -
_2020-04-08 15:39 OpenAPI 3.1 and JSON Schema-09_

https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09 <= new phil sturgeon article celebrating convergence +
https://stoplight.io/open-source/spectral/ <= Spectral, an Open Source JSON/YAML Linter +
https://swagger.io/specification/ <= version 3.0.3

- - -
_2020-01-14 12:50 schema across TAP components_

? json schema vs xml (midPoint)

- - -

